### DISCUSSION TITLE
Is there a way to see when a epoch is finished?

### DISCUSSION THREAD

**Discussion by samricotta** [babylonlabs-io/babylon#742] [Q&A]

**Comment by samricotta** [comment]
To query the current epoch, you can use  babylond q epoching epoch
```
babylond q epoching epoch
epoch:
  current_epoch_interval: "360"
  epoch_number: "262"
  first_block_height: "93961"
  last_block_time: null
  sealer_app_hash_hex: ""
  sealer_block_hash: ""
```
  
And if the epoch is finilized, you can see it has the `last_block_time,` `sealer_app_hash_hex` and `sealer_block_hash`

```
babylond q epoching  epoch 261
epoch:
  current_epoch_interval: "360"
  epoch_number: "261"
  first_block_height: "93601"
  last_block_time: "2025-01-20T06:35:23.115042585Z"
  sealer_app_hash_hex: 8ec98035cd0dfa41cd06f7c27abdea31110769f1d03e2893b51de70971d1d477
  sealer_block_hash: 589c00af29e6d5bfb2604b3a6adead4df3fff41a8a8d181f0daceda972dd1831
```
