### ISSUE TITLE
[v1.1.0] Error while syncing the bbn-test-5 node

### ISSUE THREAD

**Issue by saravadeanil** [babylonlabs-io/babylon#1225]
Hi, I tried to restore the node using https://polkachu.com/testnets/babylon/snapshots and release v1.1.0 & v1.0.1 but getting below error.

```
failed to load latest version: version of store feeibc mismatch root store's version; expected 1203545 got 0; new stores should be added using StoreUpgrades
```

Any suggestions?

**Comment by RafilxTenfen** [comment]
@saravadeanil can you share more details? The exaclty snapshot link you used and `babylond version --long | grep :

**Comment by saravadeanil** [comment]
@RafilxTenfen Thanks for your message. Please find the details.

```
bash-5.1$ babylond version --long | grep :
build_deps:
build_tags: netgo,muslc,mainnet
commit: ced926192aba4cfdad040d5c99691cac8b8afdbf
cosmos_sdk_version: v0.50.12
go: go version go1.23.8 linux/amd64
name: babylon
server_name: babylond
version: HEAD-ced926192aba4cfdad040d5c99691cac8b8afdbf
```

Snapshot link:- https://snapshots.polkachu.com/testnet-snapshots/babylon/babylon_1203544.tar.lz4

**Comment by saravadeanil** [comment]
Actually I am using docker environment. Ant specific image version/tag I should be using?

**Comment by RafilxTenfen** [comment]
babylon testnet upgraded to v2rc4 today, I would recommend you to use a state sync after the upgrade and use 
`babylonlabs/babylond:v2.0.0-rc.4-testnet`

**Comment by saravadeanil** [comment]
Thanks for sharing it.

Just to confirm if my understanding is correct, I should be using image `babylonlabs/babylond:v2.0.0-rc.4-testnet` and using the snapshot from https://snapshots.polkachu.com/testnet-snapshots/babylon/babylon_1203544.tar.lz4 and sync the node?

**Comment by RafilxTenfen** [comment]
I think it should be another snapshot link https://snapshots.polkachu.com/testnet-snapshots/babylon/babylon_1206769.tar.lz4

![Image](https://github.com/user-attachments/assets/f3986d7d-fb49-4a88-95b2-e60812a3a2e6) 

But yeah, correct image  `babylonlabs/babylond:v2.0.0-rc.4-testnet`

**Comment by saravadeanil** [comment]
@RafilxTenfen I am getting a new error now using the above snapshot

```
version: "3.8"
services:
  babylond:
    container_name: babylon_node
    image: babylonlabs/babylond:v2.0.0-rc.4-testnet
    volumes:
      - /mnt/babylon:/home/babylon/.babylond
    ports:
      - "26657:26657"
      - "9090:9090"
      - "26656:26656"
    restart: always
    tty: false
    command: >
      babylond start
      --chain-id="bbn-test-5"
      --home="/home/babylon/.babylond"
      --bls-password-file="/home/babylon/.babylond/config/bls_password.txt"
      --p2p.persistent_peers="fe62e0a38eb7694080c83a84225a6bb33be01fed@babylon-testnet-rpc-pruned-1.nodes.guru:55706,4a3dd7deb4770c06e05849a4128fea1a7439a9d9@65.109.106.210:20656"
      --p2p.seeds="fe62e0a38eb7694080c83a84225a6bb33be01fed@babylon-testnet-rpc-pruned-1.nodes.guru:55706,4a3dd7deb4770c06e05849a4128fea1a7439a9d9@65.109.106.210:20656,e1cec61b15e9e4806a8fd2f71f06fdc9f6038a5b@65.109.113.233:20656,c65d958dde89859e174227b296e1692de3b15b87@65.108.98.168:26656,f8b81bf5b788ee7cfe2b427bf727613158146ca9@95.217.60.90:26656,e4896f7d7d4d94a69fb2583f16f22ff3fc9212f6@65.109.111.234:60656,ce183b5f345e13e25fc72d27af8466826754b688@65.108.230.161:60656"
```

```
6:39AM INF ABCI Handshake App Info hash=E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855 height=0 module=consensus protocol-version=0 software-version=v2.0.0-rc.4
6:39AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
6:39AM INF InitChain chainID=bbn-test-5 initialHeight=1 module=server
6:39AM INF initializing blockchain state from genesis.json module=server
6:39AM INF Closing application.db module=server
6:39AM INF Closing snapshots/metadata.db module=server
panic: unknown field "inflation" in types.Minter

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc00111f58e?, {0xc0005e6d80?, 0x1?, 0x4c8f625?}, {0x672d930?, 0xc0041c07f0?})
	github.com/cosmos/cosmos-sdk@v0.50.13/codec/proto_codec.go:219 +0x3b
github.com/babylonlabs-io/babylon/v2/x/mint.AppModule.InitGenesis({{{0x683d8f0, 0xc001ee13f0}}, {{0x67769d0, 0xc001ee13f0}, {0x6711ea0, 0xc0016de320}, {0x67135a0, 0xc001bc3e80}, {0x7f7b99331200, 0xc00176ca08}, ...}, ...}, ...)
	github.com/babylonlabs-io/babylon/v2/x/mint/module.go:120 +0x94
```
